spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel3.cloudtype.app:31951/dev01?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: user
    password: 1234
