spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel3.cloudtype.app:31951/dev01?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: user
    password: 1234

  # use Spring-Swagger-Doc
springDoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

# Base Url 설정
server:
  servlet:
    context-path: /api/

